jobs:
    test:
        executor:
            name: node/default
            tag: '14.15'
        steps:
            - checkout
            - node/install-packages:
                  pkg-manager: yarn
            - run:
                  command: yarn run test
                  name: Run YARN tests
            - codecov/upload:
                  file: coverage/coverage-final.json
            - run:
                  name: Install JUnit coverage reporter
                  command: yarn add --dev jest-junit
            - run:
                  name: Run tests with JUnit as reporter
                  command: yarn run test --ci --runInBand --reporters=default --reporters=jest-junit
                  environment:
                      JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
            - store_test_results:
                  path: ./reports/junit/
            - store_artifacts:
                  path: ./reports/junit
orbs:
    node: circleci/node@4.1.0
    codecov: codecov/codecov@1.0.2
version: 2.1
workflows:
    test_my_app:
        jobs:
            - test
