jobs:
    test:
        executor:
            name: node/default
            tag: '14.15'
        steps:
            - checkout
            - node/install-packages:
                  pkg-manager: yarn
            - run:
                  command: yarn run test
                  name: Run YARN tests
            - store_test_results:
                  path: coverage/test-result.json
            - codecov/upload:
                  file: coverage/coverage-final.json
orbs:
    node: circleci/node@4.1.0
    codecov: codecov/codecov@1.0.2
version: 2.1
workflows:
    test_my_app:
        jobs:
            - test
