const user = {
    name: {},
    title: {},
    alias: {},
    role: {},
    profile: {},
    nps_score: {},
    description: {},
    call_steering_description: {},
    password: {},
    extension: {},
    acl: {},
    clid: {},
    static: {},
    allowRecordingInterruption: {},
    recordAtCallStart: {},
    algo: {},
    email: {},
    emailAuth: {},
    icon: {},
    emoji: {},
    options: {},
    backoffice_user: {},
    deactivated: {},
    deleted: {},
};

const account = {
    name: {},
    title: {},
    sla: {},
    user: user,
    description: {},
    created: {},
    edited: {},
    customFields: {},
};
const contact = {
    name: {},
    title: {},
    firstname: {},
    lastname: {},
    account: account,
    user: user,
    description: {},
    nps_score: {},
    created: {},
    edited: {},
    duplicateContacts: {},
    notDuplicateContacts: {},
    customFields: {},
};

export const list = {
    activity: {
        name: {},
        ticket: {},
        title: {},
        important: {},
        action: {},
        type: {},
        item: {},
        queue: {},
        user: user,
        contact: contact,
        survey: {},
        record: {},
        priority: {},
        options: {},
        description: {},
        time: {},
        time_wait: {},
        time_open: {},
        time_close: {},
        baw: {},
        aaw: {},
        duration: {},
        ringing_time: {},
        created_by: user,
        statuses: {},
    },
    user: user,
    interaction: {
        contact: contact,
        title: {},
        phone: {},
        email: {},
    },
};
